import regex

exists: (str, any) -> bool = lambda o: str, ocds: any -> bool {
    resource = get(ocds, o, {})
    resource != {}
}

get = lambda x: any, y: str, d: any -> any {
    """
    Get an item from a dictionary using a dot separated path.
    If the item is not found, return a default value.
    """
    p = regex.split(y, "\.")
    c = p[0]
    y = ".".join(p[1::])
    x[c] if len(p) == 1 and c in x else d if c not in x else get(x[c], y, d)
}