apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbackstages.sa.upbound.io
spec:
  compositeTypeRef:
    apiVersion: sa.upbound.io/v1alpha1
    kind: XBackstage
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-backstagexbackstage
    step: xbackstage
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
